version: "3"

services:
  nodemoleculer:
    build: .
    container_name: mymoleculernode
    command: tail -f /dev/null
    volumes:
      - .:/code
    ports:
      - "8000:8000"
      - "5858:5858"
      - "3000:3000"
